### ISSUE TITLE
Rule proposal: Ban postfix conditionals

### ISSUE THREAD

**Issue by ptarjan** [rubocop-hq/rubocop#2788]
I'd like to ban postfix conditionals. I didn't see anything like that in the rule set.

These would be autofixed:

```
# bad
foo if bar
# good
if bar
  foo
end
```

```
# bad
i += 1 while foo
# good
while foo
  i += 1
end
```

The former is the inverse of `IfUnlessModifier` and the latter is the inverse of `WhileUntilModifier`

**Comment by bbatsov** [comment]
PRs welcome. :-)

**Comment by jawshooah** [comment]
A more descriptive issue title would probably be welcome as well for the maintainers' sake.

**Comment by ptarjan** [comment]
@jawshooah sorry, I was expecting a slower response :) I'll bais more toward getting a better initial Issue for rubocop. Thanks.

**Comment by mikestok** [comment]
I think that `foo if bar` is fine until it the condition or the thing being modified becomes more complex, for example `foo and bar if baz || plugh`.  My reasoning is that the cognitive load goes up as you need to remember precedence and mentally break things down in the complex case, but a simple `foo unless bar` is a useful concise idiom.

If there were to be a cop for "banning" postfix modifiers then please consider letting the default be to allow simple ones and have complete or no prohibition settings too.

**Comment by jonas054** [comment]
@ptarjan I support the idea (although I personally love modifier expressions).

> The latter is the inverse of WhileUntilModifier.

And the former is the inverse of `IfUnlessModifier`. I think it makes sense to do the implementation in existing cops by introducing configuration like
```yaml
Style/IfUnlessModifier:
  MaxLineLength: 80
  # The `modifier` style prefers modifier over the non-modifier form if the
  # modifier form of the expression fits on a line that's no longer than
  # `MaxLineLength`. The `no_modifier` style always prefers the non-modifier
  # form.
  EnforcedStyle: modifier
  SupportedStyles:
    - modifier
    - no_modifier
```
(Feel free to improve the wording of the comment!)

> allow simple ones

Can of worms, @mikestok. What is simple? That's going to keep us busy for a while.
