### ISSUE TITLE
ClosingParenthesisIndentation doesn't leave ) to the left edge

### ISSUE THREAD

**Issue by ptarjan** [rubocop-hq/rubocop#2791]
It correctly works for parameters

```
# good
foo(
  a,
  b,
)
```

but it complains about 

```
# incorrect lint error
foo({
  a: b
},
)
```

which rubocop suggests I do

```
# incorrect autofix
foo({
  a: b
},
   )
```

Similarly if I leave a param on the first line, it won't let me left alignt

```
# incorrect lint error
foo(a,
  b,
)
```

If this is intentional behavior, can I get an option in the same vein as 

```
Style/IndentHash:
  EnforcedStyle: consistent
Style/IndentArray:
  EnforcedStyle: consistent
Style/FirstParameterIndentation:
  EnforcedStyle: consistent
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
```

which leaves these on the left?
