### ISSUE TITLE
Rule proposal: Multiline Method Calls New Lines

### ISSUE THREAD

**Issue by ptarjan** [rubocop-hq/rubocop#2801]
I'd like to enforce 2 space indenting for anything multiline.

Some examples:

```
# bad
foo(a,
  b)

# good
foo(
  a,
  b
)
```

```
# bad
foo({a: b
})

# good
foo({a: b})
foo({
  a: b
})
```

```
# bad
foo({a, b}, {
  c: d
})

# good
foo({
  a: b
}, {
  c: d
})
foo(
  {
    a: b
  }, {
    c: d
  }
)
foo(
  {
    a: b
  }, 
  {
    c: d
  }
)
```

```
# bad
foo({a: b},
c
)

# good
foo(
  {
    a: b,
  },
  c
)
foo({a: b}, c)
```

Is there something like this already that I can copy?

**Comment by alexdowad** [comment]
Somehow I think we already have a style like this somewhere....

**Comment by ptarjan** [comment]
@alexdowad I didn't see it in my autocreated todo file. Any idea what it would be called?

**Comment by ptarjan** [comment]
ping @alexdowad

**Comment by ptarjan** [comment]
Doing this is close:

```
Style/FirstArrayElementLineBreak:
  Enabled: true
Style/FirstHashElementLineBreak:
  Enabled: true
Style/FirstMethodArgumentLineBreak:
  Enabled: true
Style/FirstMethodParameterLineBreak:
  Enabled: true
Style/MultilineArrayBraceLayout:
  Enabled: true
Style/MultilineHashBraceLayout:
  Enabled: true
Style/MultilineMethodCallBraceLayout:
  Enabled: true
Style/MultilineMethodDefinitionBraceLayout:
  Enabled: true
```
