### ISSUE TITLE
Style/ElseAlignment should have a consistent option

### ISSUE THREAD

**Issue by ptarjan** [rubocop-hq/rubocop#2854]
We'd like to have something like these:

```
Style/IndentHash:
  EnforcedStyle: consistent
Style/IndentArray:
  EnforcedStyle: consistent
Style/FirstParameterIndentation:
  EnforcedStyle: consistent
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
```

but would change this code:

```
foo = if bar
  1
      else
  2
end
```

into this

```
foo = if bar
  1
else
  2
end
```

**Comment by ptarjan** [comment]
Similar to https://github.com/bbatsov/rubocop/issues/2849

**Comment by chrisnicola** [comment]
Agreed. Did this break recently? I wasn't having problems with this until today.

**Comment by ptarjan** [comment]
@chrisnicola I turned it on for our repo yesterday, so no idea. Can you not repro?

**Comment by chrisnicola** [comment]
No I can I came here to see if there was a way to set it properly. Aligning with the `if` statement makes this look completely ridiculous. I'm basically going to have to disable it now.

**Comment by chrisnicola** [comment]
This may be related: https://github.com/bbatsov/rubocop/issues/2399

I'm seeing a number of issues related to this recently, so I'm thinking perhaps something changed.

**Comment by chrisnicola** [comment]
So this does work if you set

```
Lint/EndAlignment:
  AlignWith: variable
```

Oddly enough a `start_of_line` option was added recently which seems to have a bug where it properly sets the alignment of `end` but complains about the indentation width of the content of the blocks.

Also it doesn't work if you use `<<` instead of `=` but the `ConditionalAssignement` cop complains now if you don't use `<<`. The whole thing is a mess but I would suggest closing these issues. Most of the ones you've open seem to be duplicates and they are supposed to work but there are a couple bugs.

**Comment by jonas054** [comment]
Yes, there seems to be a bug in `Lint/EndAlignment`'s handling of the `start_of_line` option.

**Comment by jonas054** [comment]
The configuration you need for making `rubocop -a` turn
```ruby
foo = if bar
  1
      else
  2
end
```
into
```ruby
foo = if bar
  1
else
  2
end
```
is
```yaml
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true
```
I'm closing the issue. Let me know if you disagree, @ptarjan.
