### ISSUE TITLE
Style/TrailingCommaInArguments false positive with interpretation of multi-lined arguments?

### ISSUE THREAD

**Issue by brandonweiss** [rubocop-hq/rubocop#3586]
If I set this configuration:

``` yaml
Style/TrailingCommaInArguments:
  Enabled: true,
  EnforcedStyleForMultiline: consistent_comma
```

Then it enforces this code should have a comma like this:

``` ruby
EmailWorker.perform_async({
  subject: "hey there",
  email: "foo@bar.com"
},)
```

This doesn't seem right to me? It's a nuanced difference, but I don't consider this multi-lined arguments—the argument actually starts on the same line as the parentheses. The argument itself is multi-lined for readability, but the arguments aren't multi-lined. This is what I think multi-lined arguments look like:

``` ruby
EmailWorker.perform_async(
  "foo",
  "bar,
)
```

Or in the context of a hash:

``` ruby
EmailWorker.perform_async(
  {
    subject: "hey there",
    email: "foo@bar.com"
  },
)
```

Thoughts?
