### ISSUE TITLE
`Style/MultilineIfModifier` conflicts to `Style/GuardClause`

### ISSUE THREAD

**Issue by nepalez** [rubocop-hq/rubocop#3709]
The first example breaks `Style/MultilineIfModifier`

```ruby
if foo
  bar.baz
     .qux
end
```

The second one breaks `Style/GuardClause`

```ruby
bar.baz
   .qux if foo
```

**Comment by mikegee** [comment]
I can't get the first example to return an offense. Please post your Rubocop config.

**Comment by jaronson** [comment]
Well, well, well, well. Got Mr. @mikegee over here looking to be able to reproduce an issue.

Here's what I can see.

Given this code:

``` ruby
def upload_owner_image
  image = owner_params.delete(:image)
  if image.present?
    owner_params[:image_path] = upload_image(
      :owner,
      image
    )
  end
end
```

This is the complaint:

```
lib/resources/owners.rb:36:11: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
          if image.present?
```

Corrected to:

``` ruby
def upload_owner_image
  image = owner_params.delete(:image)
  owner_params[:image_path] = upload_image(
    :owner,
    image
  ) if image.present?
end
```

Complains with:

```
lib/resources/owners.rb:36:11: C: Style/MultilineIfModifier: Favor a normal if-statement over a modifier clause in a multiline statement.
          owner_params[:image_path] = upload_image( ...
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Ad infinitum.

Here's my cops.

```
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 360

Metrics/ModuleLength:
  Max: 360

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/TrivialAccessors:
  IgnoreClassMethods: true

Style/MutableConstant:
  Enabled: true

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SignalException:
  EnforcedStyle: only_fail

Style/IndentArray:
  EnforcedStyle: consistent
```
