### ISSUE TITLE
No such file or directory @ rb_sysopen - $HOME/enabled.yml

### ISSUE THREAD

**Issue by mooreniemi** [rubocop-hq/rubocop#4035]
## Expected behavior

Within a [rails project](https://github.com/mooreniemi/peeps), I ran:
```
gem install rubocop
Fetching: rubocop-0.47.1.gem (100%)
Successfully installed rubocop-0.47.1
Parsing documentation for rubocop-0.47.1
Installing ri documentation for rubocop-0.47.1
Done installing documentation for rubocop after 10 seconds
1 gem installed
rubocop spec/acceptance/contacts_spec.rb
```

And expected normal rubocop output.

## Actual behavior

Instead I saw this output:

```
No such file or directory @ rb_sysopen - /Users/Alex/enabled.yml
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:153:in `read'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:153:in `load_yaml_configuration'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:34:in `load_file'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:91:in `block in base_configs'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:79:in `map'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:79:in `base_configs'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader_resolver.rb:21:in `resolve_inheritance'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:42:in `load_file'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_loader.rb:107:in `configuration_from_file'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/config_store.rb:44:in `for'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/cli.rb:93:in `apply_default_formatter'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/lib/rubocop/cli.rb:25:in `run'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/bin/rubocop:13:in `block in <top (required)>'
/Users/Alex/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/Alex/.rvm/gems/ruby-2.2.3/gems/rubocop-0.47.1/bin/rubocop:12:in `<top (required)>'
/Users/Alex/.rvm/gems/ruby-2.2.3/bin/rubocop:22:in `load'
/Users/Alex/.rvm/gems/ruby-2.2.3/bin/rubocop:22:in `<main>'
/Users/Alex/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/Alex/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

## Steps to reproduce the problem

This was on a fresh project with a fresh install of rubocop. Perhaps the problem is related to rvm?

I'm unsure what other details I can give to reproduce. I imagine this must be something wrong with my system, but I can't detect what. FWIW, I also ran the following because it has helped resolve issues in the past:

```
gem update --system
Latest version currently installed. Aborting.
```

## RuboCop version

```
rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.2.3 x86_64-darwin14)
```

**Comment by mooreniemi** [comment]
I also tried installing ruby-2.4.0 in rvm, then a fresh install of bundler and rubocop, same error.

**Comment by mikegee** [comment]
Do you have a `.rubocop.yml` file? Please post that if you do.

**Comment by mooreniemi** [comment]
@mikegee 

```
cat .rubocop.yml
AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**.rb
    - db/seeds/**.rb
    - db/seeds.rb
    - db/schema.rb
    - client/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - test/test_helper.rb
    - config/**/*
    - lib/scraper/*

Documentation:
  Enabled: false

LineLength:
  Max: 80

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
```
