### ISSUE TITLE
auto-gen-config no longer add Rails cops

### ISSUE THREAD

**Issue by graaff** [rubocop-hq/rubocop#4238]
With rubocop 0.48.1 the auto-gen-config option no longer adds Rails cops to the todo file. This also appeared to be the case with rubocop 0.48.0, but I could not test this well due to #4225 at the time.

Initially I thought this may be related to the new TargetRailsVersion option, but this happens both with and without this option in .rubocop.yml. I have tested it with "TargetRailsVersion: 4.2"

0.48.1 (using Parser 2.3.3.1, running on ruby 2.2.7 x86_64-linux)

**Comment by graaff** [comment]
I just tested with another internal Rails project and here the Rails cops are correctly added with auto-gen-config.

Any hints on how to debug this further?

**Comment by d-lebed** [comment]
Do you run it with -R key? Does .rubocop.yml in other project contain
```yaml
Rails:
  Enabled: true
```
?

**Comment by graaff** [comment]
Rails is enabled in both projects in .rubocop.yml. I normally don't use -R. However, using -R does fix the issue. With "rubocop -R --auto-gen-config" a todo file is created that includes the Rails cops, and afterwards "rubocop" (with or without -R) no longer shows failing cops. This is the .rubocop.yml for this project:

```yaml
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - db/schema.rb
    - features/**/*

Lint/UnreachableCode:
  Exclude:
    - db/migrate/**/*

Security/Eval:
  Exclude:
    - config/deploy.rb
    - lib/tasks/check.rake
    - script/**/*

Style/DoubleNegation:
  Enabled: false

Style/FileName:
  Exclude:
    - script/**/*
    - theme/**/*

Style/SpaceInsideStringInterpolation:
  Enabled: false
```
