### ISSUE TITLE
[Metrics/***Length] Is it possible to exclude heardocs line count?

### ISSUE THREAD

**Issue by KosukeOhmura** [rubocop-hq/rubocop#5394]
## Expected behavior

Hi,
Metrics/ClassLength, Metrics/MethodLength and other cops for line count doesn't ignore heardocs.
I can ignore it by writing `# rubocop:disable Metrics/MethodLength` for all points that have heardocs, but it is not a smart way. Can I configure to ignore heardoc's line count?

## Actual behavior

When I write this code:

```
def self.list(gender)
  sql = <<-SQL
    SELECT
      uuid
      ,name
      ,tel
      ,email
      ,gender
      ,created_at
      ,updated_at
    FROM
      get_member_list(p_gender := :gender)
  SQL

  find_by_sql([sql, { gender: gender }])
end
```

I get error `C: Metrics/MethodLength: Method has too many lines.`.

## Steps to reproduce the problem

Write a method that have a long heardoc and then execute `rubocop`.

my .rubocop.yml is this:

```
AllCops:
  TargetRubyVersion: 2.5
AsciiComments:
  Enabled: false
Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s)#']

Style/EmptyMethod:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  AutoCorrect: true
```

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.5.0 x86_64-linux)
```

Thanks
