### ISSUE TITLE
Exclude options not inherited from gem

### ISSUE THREAD

**Issue by henrik** [rubocop-hq/rubocop#5536]
This seems related to #3744.

I have the latest released Rubocop, 0.52.1.

In my Rails project, the .rubocop.yml file is just this:

```
inherit_gem:
  barsoom_utils: shared_rubocop.yml
```

The shared_rubocop.yml file is this: https://github.com/barsoom/barsoom_utils/blob/master/shared_rubocop.yml

And contains:

```
AllCops:
  DisabledByDefault: true
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - node_modules/**/*

…
```

But Rubocop in my Rails app does not respect these ignores, after moving them to the shared gem. Is this by design? Can I change something to get the desired behaviour? Or is it a bug?

I have seen https://github.com/bbatsov/rubocop/pull/5488, but if I understood #3744 correctly, then the behaviour I'm expecting should already exist.
