### ISSUE TITLE
Rubocop "-a" changes the return type of the method

### ISSUE THREAD

**Issue by execat** [rubocop-hq/rubocop#5669]
The rewritten method on executing using "-a" puts the comma in the wrong position for the method. This might have something to do with the `Style/TrailingCommaInHashLiteral` rule (see below).

This is dangerous because the comma changes the return type of the method from a hash to an array because of the comma. Instead of returning type `{}` now the method returns type `[{}, nil]`.

--------

## Expected behavior

`lol.rb`:
```
def lol
  { 
    one: 1,
    two: '',
    three: 0,
  }
end
```

## Actual behavior

`lol.rb`:
```
def lol
  ret = { one: 1,
          two: '',
          three: 0 },
        ret
end
```

## Steps to reproduce the problem

1. Save this as `lol.rb`:
```
def lol
  ret = { :one => 1,
          :two => '',
          :three => 0
  }
  ret
end
```

2. Use this `rubocop.yml`:

```
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Layout/AlignParameters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3+
  Exclude:
    - '**/*.gemspec'
    - '**/Rakefile'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/MutableConstant:
  Enabled: false
```

3. Run `rubocop -a lol.rb`

## RuboCop version

```
$ rubocop -V
0.53.0 (using Parser 2.5.0.3, running on jruby 2.3.3 java)
```
