### ISSUE TITLE
Rubocop "-a" changes the meaning of the ternary condition

### ISSUE THREAD

**Issue by execat** [rubocop-hq/rubocop#5771]
The rewritten line on executing using "-a" removes the parenthesis which changes the meaning of the condition.

--------

## Expected behavior

`lol.rb`:
```
result = [1, 2, 3].include?(1) ? 'omg' : 'lol'
OR
result = ([1, 2, 3].include? 1) ? 'omg' : 'lol'
puts result
```
The result of this evaluation is "omg".

## Actual behavior

`lol.rb`:
```
result = [1, 2, 3].include? 1 ? 'omg' : 'lol'
puts result
```
The result of this evaluation is 'false'.

## Steps to reproduce the problem

1. Save this as `lol.rb`:
```
result = ([1, 2, 3].include? 1) ? 'omg' : 'lol'
puts result
```

2. Use this `rubocop.yml`:
```
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Layout/AlignParameters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3+
  Exclude:
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'lib/sequel/adapters/mariadb.rb'
    - 'Guardfile'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/MutableConstant:
  Enabled: false
```

3. Run `rubocop -a lol.rb`

## RuboCop version

```
$ rubocop -V
0.54.0 (using Parser 2.5.1.0, running on ruby 2.4.0 x86_64-darwin16)
```
(But I had this issue on jruby too)
