### ISSUE TITLE
Comma at end of URI causes Rubocop to alert on LineLength

### ISSUE THREAD

**Issue by rpbaptist** [rubocop-hq/rubocop#5916]
## Expected behavior

Having the following configuration:

```yaml
Metrics/LineLength:
  Max: 80
  AllowHeredoc: true
  AllowURI: true
```

I expect this to be allowed:

```ruby
{
  confirmation_url: "https://subodomain.example.com/with_a_length_path/?and=some&more=params",
  foo: :bar
}
```

## Actual behavior

Rubocop warns that line is too long and it's because of the comma. When I reverse the keys Rubocop does recognize the URI.

```ruby

{
  foo: :bar,
  confirmation_url: "https://subodomain.example.com/with_a_length_path/?and=some&more=params"
}
```

## Steps to reproduce the problem

See above

## RuboCop version

```
> rubocop -v
0.55.0
```
