### ISSUE TITLE
Autocorrect produces invalid syntax for TrailingCommaInArrayLiteral/TrailingCommaInHashLiteral with EnforcedStyleForMultiline: comma

### ISSUE THREAD

**Issue by amarshall** [rubocop-hq/rubocop#5932]
## Expected behavior

Autocorrect does not produce invalid Ruby.

```ruby
# frozen_string_literal: true

[
  { one: 'bar',
    bar: 'baz' },
  { one: 'bar',
    bar: 'baz' },
  [1,
   2],
  [3,
   4],
]
```

## Actual behavior

Autocorrect produces invalid Ruby.

```ruby
# frozen_string_literal: true

[
  { one: 'bar',
    bar: 'baz'},,
  { one: 'bar',
    bar: 'baz' },
  [1,
    2],,
  [3,
    4],
]
```

## Steps to reproduce the problem

Create the following files:

```yaml
# rubocop.yml
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
```

```ruby
# comma-literal.rb
[
  { one: 'bar',
    bar: 'baz'
  },
  { one: 'bar',
    bar: 'baz'},
  [ 1,
    2
  ],
  [ 3,
    4
  ]
]
```

Run `rubocop -a`, then `ruby comma-literal.rb`, and witness that Ruby complains of invalid syntax:

```
comma-literal.rb:5: syntax error, unexpected ',', expecting ']'
    bar: 'baz'},,
                 ^
comma-literal.rb:7: syntax error, unexpected ',', expecting end-of-input
    bar: 'baz' },
```

## RuboCop version

```
$ rubocop -V
0.56.0 (using Parser 2.5.1.0, running on ruby 2.4.2 x86_64-darwin17)
```
