### ISSUE TITLE
Layout/ClassStructure: undefined method `first_line' for #<Parser::Source::Comment:0x00007fd0614a7ae8>

### ISSUE THREAD

**Issue by InteNs** [rubocop-hq/rubocop#6098]
I'm implementing this cop and a lot of our models seem to trigger this exception.

--------

## Expected behavior

expected the cop to autocorrect my file

## Actual behavior

error got thrown: `undefined method 'first_line' for #<Parser::Source::Comment:0x00007fd0614a7ae8>`

## Steps to reproduce the problem
`.rubocop.yml`
```yml
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    hooks:
      - before_validation
      - before_create
      - before_update
      - before_save
      - before_destroy
      - after_validation
      - after_create
      - after_update
      - after_save
      - after_destroy
    validations:
      - validates
      - validates_with
  ExpectedOrder:
    - constants
    - module_inclusion
    - table_name
    - primary_key
    - sequence_name
    - hooks
    - has_one
    - belongs_to
    - has_many
    - has_and_belongs_to_many
    - alias_attribute
    - attribute
    - keyword_attribute
    - object_attributes
    - validations
    - scope
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods
```
`app/models/locomotive.rb`
```rb
class Locomotive < ApplicationRecord
  before_save do
    if locomotive_sub_type_id_changed?
      self.locomotive_type_id = locomotive_sub_type&.wagon_type_id
    end
  end

  alias_attribute :asset_nr, :uic_code

  # TODO: create scope to split wagon types into locomotive types + wagon types
  belongs_to :locomotive_type,
    class_name: 'WagonType'

  belongs_to :locomotive_sub_type,
    class_name: 'WagonSubType'

  def uic_code_formatted
    "#{uic_code[0..1]} #{uic_code[2..3]} #{uic_code[4..7]} #{uic_code[8..10]}-#{uic_code[11]}"
  end
end
```
## RuboCop version

```
$ rubocop -V
0.57.2 (using Parser 2.5.1.0, running on ruby 2.5.0 x86_64-darwin18)
```
