### ISSUE TITLE
Autocorrect not working for Lint/UnusedMethodArgument with keyword argument

### ISSUE THREAD

**Issue by cordis-dev** [rubocop-hq/rubocop#6162]
## Expected behavior

Unused argument auto-corrected.

## Actual behavior

Unused argument not auto-corrected.

## Steps to reproduce the problem

Given `.rubocop.yml`:
```yml
AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.4

Lint/UnusedMethodArgument:
  Enabled: true
```

and `test.rb`:
```ruby
class Test
  def self.method_with_keyword_arg(test: false)
    return nil;
  end
end
```
run 
```
rubocop --cache false --auto-correct test.rb
```

## RuboCop version

```
$ rubocop -V
0.58.2 (using Parser 2.5.0.3, running on ruby 2.4.4 x64-mingw32)
```
