### ISSUE TITLE
Multiline keyword arguments indentation is inconsistent between method definitions and calls

### ISSUE THREAD

**Issue by robotdana** [rubocop-hq/rubocop#6291]
**I would be happy to work on this as a PR if you're happy with this proposed solution**

**Is your feature request related to a problem? Please describe.**
Two things relating to keyword arguments:
1. There is inconsistency between method calls and method definitions. `Layout/AlignHash` is in charge of keyword arguments in method calls, and `Layout/AlignParameters` is in charge of keyword arguments in method definitions.

2. To me keyword arguments are more a type of parameter more than a type of hash. I'd like it to be possible to always align them using the rules for `Layout/AlignParameters`

with default config, rubocop currently thinks this is correct:
```ruby
def method(position_1, keyword: true,
           keyword_2: true)
end

method(position_1, keyword:   true,
                   keyword_2: true)
```
**Describe the solution you'd like**

When `Layout/AlignHash: EnforcedLastArgumentHashStyle` is ignored, i'd like keyword arguments indentation to instead be controlled by `Layout/AlignParameters`, and when `EnforcedLastArgumentHashStyle` is not ignored, I'd like keyword arguments to be controlled by `Layout/AlignHash`

For example, with the following config
```yml
Layout/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignored
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
```
```ruby
def method(position_1, keyword: true,
  keyword_2: true)
end
method(position_1, keyword: true,
  keyword_2: true)
```
---
```yml
Layout/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignored
Layout/AlignParameters:
  EnforcedStyle: with_first_parameter
```
```ruby
def method(position_1, keyword: true,
           keyword_2: true)
end
method(position_1, keyword: true,
       keyword_2: true)
```
---
with default config
```ruby
def method(position_1, keyword:   true,
                       keyword_2: true)
end
method(position_1, keyword:   true,
                   keyword_2: true)
```

**I would be happy to work on this as a PR if you're happy with this proposed solution**
