### ISSUE TITLE
Style/TrailingCommaInArrayLiteral: Do not check for coma if there is a square bracket

### ISSUE THREAD

**Issue by GCorbel** [rubocop-hq/rubocop#6403]
**Description**

I have those rules defined : 

```
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
```

And this code : 

```
content_sources(:answers_domain_test).update(
  foreign_categories: [{
    id: "1",
    optional: false,
    item_name: "Gimme the color pnuk",
    name: "Color",
    categories: [{ id: "123", name: "Red" }, { id: "456", name: "Blue" }],
  }]
)
```

And I have this error message : 

```
C: Style/TrailingCommaInArrayLiteral: Put a comma after the last item of a multi
line array.
          }]
          ^
```

So I have to replace the `}]` by `},]` which give : 

```
content_sources(:answers_domain_test).update(
  foreign_categories: [{
    id: "1",
    optional: false,
    item_name: "Gimme the color pnuk",
    name: "Color",
    categories: [{ id: "123", name: "Red" }, { id: "456", name: "Blue" }],
  },]
)
```

I find this code ugly.

**Possible solution**

I suppose Rubocop can check if there is a curly brace or square bracket just after the curly brace in problem.

**Other option**

Disable the rule.
