### ISSUE TITLE
Layout/BlockAlignment options behave in mirrored fashion

### ISSUE THREAD

**Issue by Epigene** [rubocop-hq/rubocop#6497]
Layout/BlockAlignment cop `start_of_block` and `start_of_line` options seem to do the opposite of what they say.

Using `start_of_block` aligns to the beginning of line, and using `start_of_line` aligns to beginning of expression.

--------

## Given rubocop config

```yaml
AllCops:
  DisabledByDefault: true 
  UseCache: false
  TargetRubyVersion: 2.3.4

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line 
  SupportedStylesAlignWith:
    - either
    - start_of_block
    - start_of_line 
```

## What is going on

```rb
# offensive code
class DefinedVehicle < ActiveRecord::Base
  scope :of_manufacturing_year, -> (year=nil) {
    where(year: year.to_i)
                 }
end

# expected code after autofix
class DefinedVehicle < ActiveRecord::Base
  scope :of_manufacturing_year, -> (year=nil) {
    where(year: year.to_i)
  }
end

# real code after autofix
class DefinedVehicle < ActiveRecord::Base
  scope :of_manufacturing_year, -> (year=nil) {
    where(year: year.to_i)
                                }
end
```

Happens with both brace and `do .. end` delimiters.

## RuboCop version

```
$ rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.3.4 x86_64-darwin17)
```
