### ISSUE TITLE
Interaction between disabled Style/MutableConstant and consistent_comma in Style/TrailingCommaInArrayLiteral

### ISSUE THREAD

**Issue by searls** [rubocop-hq/rubocop#6498]
Given config:

```yaml
Style/MutableConstant:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
```

And listing:

```ruby
STUFF = [ 1,
          3,
          4,
          5
        ]

THINGS = {
    :oh => :io,
    :hi => 'neat'
    }
```

Will produce:

```ruby
STUFF = [1,
         3,
         4,
         5,],

        THINGS = {
          oh: :io,
          hi: 'neat'
        }
```

Obviously the indentation isn't right. Note also the trailing `],` which results in `STUFF` actually having `THINGS` as its final element, making the autocorrection break the code.

I have little clue how to go about fixing this, but one thing worth noting is that the problem does not occur if there is a newline before the first element in `STUFF`
