### ISSUE TITLE
"SpaceInsideArrayLiteralBrackets" with multiline array literals with "compact" option

### ISSUE THREAD

**Issue by nburns** [rubocop-hq/rubocop#6529]
## Expected behavior

Multiline array literals would be allowed to be indented with spaces.
I would expect the following code to be valid with the following rubocop config:
file.rb:
```
multiline = [
  [ 1, 2, 3, 4 ],
  [ 3, 4, 5, 6 ],
]
```

.rubocop.yml:
```
AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: compact
```

## Actual behavior
There was an error I wouldn't expect
```
>>> rubocop file.rb --auto-correct
Inspecting 1 file
C

Offenses:

file.rb:1:14: C: [Corrected] Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside array brackets.
multiline = [


1 file inspected, 1 offense detected, 1 offense corrected
```

## Steps to reproduce the problem
1. create a ruby file with the contents of "file.rb" above
2. create a rubocop config with the contents of "./rubocop.yml" above
3. run rubocop, see that it prints an offense

## RuboCop version
```
rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17)
```
