### ISSUE TITLE
UnneededDisable: Weird false positives

### ISSUE THREAD

**Issue by zor-el** [rubocop-hq/rubocop#6811]
Observed behavior:

``` bash
$ rubocop .
Inspecting 213 files
......W....^C
Exiting... Interrupt again to exit immediately.
.

Offenses:

app/models/account.rb:1:1: W: Lint/UnneededDisable: Unnecessary disabling of Rails/ApplicationRecord.
# rubocop:disable Rails/ApplicationRecord
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/models/account.rb:15:17: W: Lint/UnneededDisable: Unnecessary disabling of Rails/Delegate.
  def licensed? # rubocop:disable Rails/Delegate
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

12 files inspected, 2 offenses detected
$ rubocop app/models/account.rb 
Inspecting 1 file
.

1 file inspected, no offenses detected
$ 
```

- `rubocop .` reports false positives  (the cops are NOT disabled in .rubocop.yml)
- `rubocop OFFENDING-FILE.rb` says everything is ok (as it should be).
- Note the `^C` interrupt is just to avoid clutter here. The behavior is the same when rubocop runs uninterrupted.

Expected behavior: `rubocop .` should report no issues, or at least both invocations should report the same offenses for OFFENDING-FILE.rb.

Behavior detected with with rubocop 0.49.1, and reproduced with rubocop 0.64.0

**UPDATE 1:** `rubocop */` shows no offenses either.

**UPDATE 2:** I had to disable caching to reproducibly observe the effect.

**Comment by zor-el** [comment]
Hey @rrosenblum, thanks for responding.

I don't think it's working normally though:

1. AFAIK `rubocop:disable` does not work across files, and `rubocop:disable Rails/ApplicationRecord` is on the 1st line of the file (as indicated by _app/models/account.rb:**1:1**_).

2. Regardless, **shouldn't `rubocop app/models/account.rb` report the same offenses for that file as `rubocop .` ?**

3. I also tried `rubocop app/ spec/ ... [all not excluded folders]` and still no offenses. Only `rubocop .` reports them.

That doesn't seem to add up, or am I missing something very fundamental?

**Comment by jonas054** [comment]
@zor-el I have not been able to reproduce. Could you show us a minimal example of the contents of `app/models/account.rb` plus `.rubocop.yml` that causes the problem to occur?

**Comment by zor-el** [comment]
@jonas054, I can, but note I tried myself to create a minimal case (just .rubocop.yml and account.rb), and could not reproduce the issue either. There is nothing special in account.rb either.

FYI, there are extending config files in the project beyond the main one, but none that affect the `app/models` folder.

``` sh
$ find . | grep 'rubocop.yml'
./tools/.rubocop.yml
./app/models/concerns/.rubocop.yml
./features/.rubocop.yml
./spec/.rubocop.yml
./.rubocop.yml
```

#### account.rb

``` ruby
class Account < ActiveRecord::Base # rubocop:disable Rails/ApplicationRecord

  has_one :license, inverse_of: :account, dependent: :destroy
  has_many :users, inverse_of: :account, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :time_zone, presence: true

  auto_strip_attributes :title, squish: true

  EXPIRATION_TIME = 7.days

  def licensed? # rubocop:disable Rails/Delegate
    license&.licensed?
  end
end
```
#### Main .rubocop.yml

```yaml
AllCops:

  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.0
  UseCache: no

  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/*_helper.rb'
    - 'lib/tasks/**/*'
    - 'try/**/*'
    - 'other/**/*'
    - '**/node_modules/**/*'
    - 'bin/*'

  DisplayCopNames: yes
  DisplayStyleGuide: yes
  ExtraDetails: yes

Rails:
  Enabled: yes

Style/TernaryParentheses:
  Enabled: no

Style/FrozenStringLiteralComment:
  Enabled: no

Style/MutableConstant:
  Enabled: no

Style/Not:
  Enabled: no

Style/StringLiterals:
  Enabled: no

Style/Documentation:
  Enabled: no

Style/SignalException:
  Enabled: no

Style/For:
  Enabled: no

Style/AndOr:
  Enabled: no

Style/FormatString:
  EnforcedStyle: percent

Style/TrailingCommaInArguments:
  Enabled: no

Style/TrailingCommaInLiteral:
  Enabled: no

Style/EmptyMethod:
  Enabled: no

Style/SymbolArray:
  Enabled: no

Style/PercentLiteralDelimiters:
  Enabled: no

Style/LambdaCall:
  Enabled: no

Layout/SpaceBeforeBlockBraces:
  Enabled: no

Layout/EmptyLinesAroundClassBody:
  Enabled: no

Layout/EmptyLinesAroundModuleBody:
  Enabled: no

Layout/EmptyLinesAroundBlockBody:
  Enabled: no

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/CaseIndentation:
  IndentOneStep: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ModuleLength:
  Max: 150

Rails/HasAndBelongsToMany:
  Enabled: no
```
