### ISSUE TITLE
Layout/CaseIndentation auto-correct not indent "end"

### ISSUE THREAD

**Issue by zw963** [rubocop-hq/rubocop#7061]
A image can describe clearly.

![image](https://user-images.githubusercontent.com/549126/58067780-4222eb00-7bc1-11e9-9e90-211575db4e7f.png)

```
 ╰─ $ rubocop -V
0.69.0 (using Parser 2.6.3.0, running on ruby 2.6.2 x86_64-linux)

```

**Comment by buehmann** [comment]
It turns out that autocorrection for cop `Layout/EndAlignment` has been disabled by default since 2015: https://github.com/rubocop-hq/rubocop/pull/1789

You could add the following to your `.rubocop.yml` to enable it:
```yaml
Layout/EndAlignment:
  AutoCorrect: true

Layout/DefEndAlignment:
  AutoCorrect: true
```
