### ISSUE TITLE
unrecognized cop Performance/Casecmp

### ISSUE THREAD

**Issue by beauraF** [rubocop-hq/rubocop#7117]
## Expected behavior

Run without warning.

## Actual behavior

```
$ [bundle exec] rubocop
Warning: unrecognized cop Performance/Casecmp found in .rubocop.yml
```

## Steps to reproduce the problem

Add:

```yaml
# .rubocop.yml

Performance/Casecmp:
  Enabled: false
```

And run:

```
$ [bundle exec] rubocop
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.71.0 (using Parser 2.6.3.0, running on ruby 2.5.3 x86_64-darwin18)
```
