### ISSUE TITLE
Wildcard excludes do not work if running within Git Bash

### ISSUE THREAD

**Issue by amyspark** [rubocop-hq/rubocop#7190]
Hey all,

I've run into a bug when using Rubocop with bash (Git Bash) under Visual Studio Code.

This is the relevant portion of .rubocop.yml:

```yaml
require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'app/views/**/*'
    - 'bin/*'
    - 'config/initializers/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'storage/**/*'
    - 'vendor/**/*'

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: start_of_line

Layout/IndentFirstArgument:
  Enabled: true

Layout/IndentFirstArrayElement:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true

Layout/IndentFirstParameter:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Metrics/BlockLength:
  Max: 80
  ExcludedMethods:
    - RSpec.describe

Metrics/LineLength:
  AutoCorrect: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Rails/FilePath:
  EnforcedStyle: slashes

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/MultipleExpectations:
  Max: 2

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'config/application.rb'
    - 'db/migrate/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
```

## Expected behavior

When running `rubocop -a`, it doesn't check excluded files.

## Actual behavior

Rubocop checks all paths including the excluded entries:
```
$ rubocop -a
Inspecting 112 files
............................................C........CCCCCCCCCCC.................................C............C.

Offenses:

config/application.rb:23:3: C: Style/Documentation: Missing top-level class documentation comment.
  class Application < Rails::Application
  ^^^^^
db/migrate/20190606220116_create_languages.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateLanguages < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606220200_create_countries.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateCountries < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606220320_create_author_types.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateAuthorTypes < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606220834_create_project_types.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProjectTypes < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606221119_create_product_types.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProductTypes < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606221403_create_areas.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateAreas < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606221457_create_sectors.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateSectors < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190606222535_create_disciplines.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateDisciplines < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190610205506_create_products.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProducts < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190612214733_create_articles.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateArticles < ActiveRecord::Migration[5.2]
^^^^^
db/migrate/20190618133227_create_product_disciplines.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class CreateProductDisciplines < ActiveRecord::Migration[5.2]
^^^^^
spec/rails_helper.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
# This file is copied to spec/ when you run 'rails generate rspec:install'
^
spec/rails_helper.rb:60:101: C: Metrics/LineLength: Line is too long. [105/100]
  # start by truncating all the tables but then use the faster transaction strategy the rest of the time.
                                                                                                    ^^^^^
spec/spec_helper.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
^
spec/spec_helper.rb:54:1: C: [Corrected] Style/BlockComments: Do not use block comments.
=begin ...
^^^^^^
spec/spec_helper.rb:100:1: C: [Corrected] Layout/CommentIndentation: Incorrect indentation detected (column 0 instead of 2).
#   Kernel.srand config.seed
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

112 files inspected, 17 offenses detected, 4 offenses corrected
```

This still happens when running Rubocop through a CMD instance (Git Bash -> `cmd` -> `rubocop -a`), so I believe there's a path construction issue somewhere.

## Steps to reproduce the problem

1. Install Rubocop and Git Bash.
2. Configure VS Code to use Git Bash's `bash` by setting `terminal.integrated.shell.windows` to  `d:\\Program Files\\Git\\bin\\bash.exe`.
3. Set up a project with excluded paths. Make sure the excluded paths have issues.
4. Run Rubocop.

## RuboCop version

`0.71.0 (using Parser 2.6.3.0, running on ruby 2.5.5 x64-mingw32)`
