### ISSUE TITLE
Style/SymbolArray autocorrect breaks `:[]`

### ISSUE THREAD

**Issue by lamont-granquist** [rubocop-hq/rubocop#7193]
here's the diff resulting from the autocorrect:

```
-      direct_access_methods = Enumerable.instance_methods + [ :[], :each, :each_index, :empty? ]
+      direct_access_methods = Enumerable.instance_methods + %i{\[\] each each_index empty?}
```

and those expressions are not equivalent:

```
% pry
[1] pry(main)> [ :[], :each, :each_index, :empty? ]
=> [:[], :each, :each_index, :empty?]
[2] pry(main)> %i{\[\] each each_index empty?}
=> [:"\\[\\]", :each, :each_index, :empty?]
```

```
% NOEXEC_DISABLE=1 rubocop --version
0.72.0
```

**Comment by lamont-granquist** [comment]
not entirely unsurprisingly `:[]=` also gets broken.

**Comment by koic** [comment]
I cannot reproduce by the default settings. Could you show a .rubocop.yml for this auto-correct?

**Comment by lamont-granquist** [comment]
I'm using `rubocop --only  Style/SymbolArray` so I don't think the contents of the .rubocop.yml matters?

The contents of the .rubocop.yml though is:

```
llCops:
  Exclude:
    - "spec/data/**/*"
    - "vendor/**/*"
    - "pkg/**/*"
    - "chef-config/pkg/**/*"
    - "habitat/**/*"
Security/Eval:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/DeprecatedClassMethods:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/ShadowedException:
  Enabled: false
Layout/AlignHash:
  Enabled: true
  EnforcedLastArgumentHashStyle: ignore_implicit
```

**Comment by pocke** [comment]
I can reproduce it with a configuration of Style/PercentLiteralDelimiters cop.

```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
```

I guess you have the cop's setting in some .rubocop.yml.
Can you confirm your .rubocop.yml? You can use `rubocop --debug` to display configuration files that are used by rubocop. I guess it includes another .rubocop.yml.

**Comment by lamont-granquist** [comment]
yeah, i just figured out the same thing.

i don't quite understand how it was picking it up but:

```
Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%I': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'
```

**Comment by lamont-granquist** [comment]
Actually its possible I ran that in isolation with --only and then saw the `%i[]`s were added and then fixed the PercentLiteralDelimiters with a global run with autocorrect on against those rules.  Although one way or another there's an autocorrect bug here, possibly two, since when the PercentLiteralDelimiters change any escaped old delimiter should become unescaped.

**Comment by buehmann** [comment]
This is actually a problem in `Style/PercentLiteralDelimiters` and relates to https://github.com/rubocop-hq/rubocop/issues/4363. The fix back then only covered the `%w` case correctly, but not `%i`.

I can reproduce the problem using the input
```ruby
%i[\[\] each each_index empty?]
```
with this configuration:
```yaml
Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%i': '{}'
```
I am going a add a PR for fixing this in a minute.
