### ISSUE TITLE
Allowing inherit_mode in AllCops

### ISSUE THREAD

**Issue by tomprats** [rubocop-hq/rubocop#7230]
I searched through all the other issues with `inherit_mode` and while there's a lot of discussion, I think they talk about changing defaults or how the inheritance is applied. I'm talking about allowing `inherit_mode` in a new place to achieve something different.

## Is your feature request related to a problem? Please describe.

`inherit_mode` can be specified for the entire config, as well as specific cops, but it cannot be specified by `AllCops`.

The main difference is that I only want to affect AllCops:Exclude. We don't want to change the `inherit_mode` for individual cops.

## Describe the solution you'd like

Allowing the following example would exclude everything in Airbnb's AllCops:Exclude as well as the local AllCops:Exclude

```
inherit_gem:
  rubocop-airbnb: .rubocop_airbnb.yml

AllCops:
  inherit_mode:
    merge:
      - Exclude
  Exclude:
    - db/schema.rb
```

## Describe alternatives you've considered

My current solution is to change the `inherit_mode` for the entire config file, but that also changes how each individual cop inherits.

```
inherit_gem:
  rubocop-airbnb: .rubocop_airbnb.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/schema.rb
```

Another option is to just copy whatever is in Airbnb's and add it to mine.
