### ISSUE TITLE
Style/PercentLiteralDelimiters doesn't detect `%{}`

### ISSUE THREAD

**Issue by vfonic** [rubocop-hq/rubocop#7266]
I was just running rubocop constantly, when it, out of a sudden, fixed one `%{ }` multi-line string delimeter to `%( )`. 🤷‍♂ 

Just next to it there are tons of not-detected `%{ }` strings.

After trying out, I've managed to narrow it down to this:

```rb
# frozen_string_literal: true

a = %{()}
puts a
```

If there are `(` and `)` (actually only `(` would do) in the string, the cop won't raise error.

Update:

```yaml
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
```
With this setup, it fails to find `%({)` as error.

## RuboCop version

```
$ rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)
```
