### ISSUE TITLE
Allow YAML aliases in .rubocop.yml file

### ISSUE THREAD

**Issue by RaymondFallon** [rubocop-hq/rubocop#7321]
## Is your feature request related to a problem? Please describe.

It is frustrating not to be able to use YAML aliasing in the `.rubocop.yml` configuration file.

Rather than putting

```yml
# .rubocop.yml

Rails/EnumUniqueness:
  some_key:
    - lots
    - of
    - values
Rails/FindBy:
  some_key:
    - lots
    - of
    - values
```
I would like to be able to say:

```yml
# .rubocop.yml

Rails/EnumUniqueness: &my_yaml_var # <- anchor
  some_key:
    - lots
    - of
    - values
Rails/FindBy:
  <<: *my_yaml_var # <- alias
```

## Describe the solution you'd like

I would like to be able to use [YAML anchors and aliases](https://yaml.org/spec/1.2/spec.html#id2765878) inside of my `.rubocop.yml` file, in order to avoid many lines of repetition. 

## Describe alternatives you've considered

I have not delved too far into how this alternative would be implement but: perhaps `allow_yaml_aliases` could be a configurable option that a user or Rubocop can set.

## Additional context

YAML anchor/aliases are essentially variables that you can set in a YAML file. When one is set it is called an `anchor`, and subsequent references to the `anchor` are called `aliases`.

I have been delving back into the history of the `aliases` params set in the [`config_loader` file](https://github.com/rubocop-hq/rubocop/blob/8cfdc57c2ca20685dae4a6ea2872bb38f544ef71/lib/rubocop/config_loader.rb#L261), and there doesn't appear to have been any strong (vocalized) reason that aliases are not allowed. I am hoping that we can simply switch this configuration from `false` to `true`.
