### ISSUE TITLE
empty line between categories for Layout/ClassStructure 

### ISSUE THREAD

**Issue by BenZhang** [rubocop-hq/rubocop#7479]
Hi,

Do you think it would be worth implementing a featuer that force the empty line between categories? My config looks like below
```
Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - attr_macros
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - callbacks
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
  Categories:
    attr_macros:
      - attr_accessor
      - enum
    association:
      - belongs_to
      - has_many
      - has_one
      - accepts_nested_attributes_for
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    callbacks:
      - before_create
      - before_save
      - before_update
      - after_create
      - after_save
      - after_update
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend
```
I would like to force the empty line between each category similar to empty line bwteen defs
```
has_many :users
has_many :location_trainer_users

validates :name, presence: true
validates :address, presence: true
validate :valid_address

before_save :set_geocode_location

scope :active_locations, -> { where(is_active: true) }
```
instead of

```
has_many :users
has_many :location_trainer_users
validates :name, presence: true
validates :address, presence: true
validate :valid_address
before_save :set_geocode_location
scope :active_locations, -> { where(is_active: true) }
```
I have implemented that locally. I am wondering whether the community would like the idea and I can create a pull request.
