### ISSUE TITLE
There is anyway to add custom deprecated methods on the DeprecatedClassMethods?

### ISSUE THREAD

**Issue by matheuslc** [rubocop-hq/rubocop#7662]
# Question
I would like to know if I can add custom deprecated methods to Rubocop DeprecatedClassMethods cops. We wrote a custom cop to add this ability in our project. So, can we do that?

If no, what do you think about that?
If yes, can you share some tips with me? I read the Ruby Docs from the Cop and some Google Search but I couldn't find anything.

# Why?
We use this solution to help us envolve our codebase through all the teams.

**Comment by rrosenblum** [comment]
As of now, there isn't a way to add custom deprecated methods. The original intention behind the cop was to flag deprecated class methods from Ruby itself. I can see where there would be value to allow users to specify some custom deprecations as well. Someone would need to come up with a good system of how to register the custom deprecations and their replacement.


This cop seems to have left its original intention already. I just noticed that it checks for `iterator?` which isn't a class method. If we allow custom deprecations, we may want to rename the cop while we are at it. Identifying class methods is significantly easier than identifying other methods because of the added context of the method call on a specific class.

**Comment by matheuslc** [comment]
I see a lot of value on it. It is a common scenario on live codebases.

We have a custom cop doing it for us. If you want, I can contact the cop developer and ask if she wants to share it with us.

In our custom cop, you can define the deprecated class, the method, the arguments and a replacement itself.

**Comment by gustavodiel** [comment]
Let's say we want to deprecate `Book#find()` and `Book#find_by(id:)` (Doesn't make much sense, but does make a point :eyes:). It'd be nice to have something like this in the config:

```yml
Lint/DeprecateMethods:
  Enabled: true
  Rules:
    - Class: Book
      Method: find
      Replacement: 'BookRepository.find_by_custom_id!'
    - Class: Book
      Method: find_by
      ArgumentName: id
      Replacement: 'BookRepository.find_by_custom_id!'
```
