### ISSUE TITLE
Ability to exclude only certain lines

### ISSUE THREAD

**Issue by woarewe** [rubocop-hq/rubocop#7683]
Hi everyone!

Could you please suggest to me about the future features of the project. Rubocop is a great tool when you start a new project, you configure your cops and your team follows them. It's amazing, but if you wanna introduce it in legacy project and run it with the param `--auto-gen-config` it creates `.rubocop.todo.yml` that disables copes for a whole file. It works great when your new code is in new files, but if you change already excluded file rubocop doesn't check it.

Maybe, are you planning to add the ability to exclude only certain lines in the way like this?
```yml
  Layout/MultilineMethodCallBraceLayout:
    Exclude:
      - 'app/controllers/users.rb:34'
```

Or It will be much better and easier to add ability to paste inline comments automatically.

If you need any type of help when you will develop this feature I will be glad to help.
Thanks for your time and attention.
