### ISSUE TITLE
Do-end blocks problem for `it`

### ISSUE THREAD

**Issue by KhadeevKamil** [rubocop-hq/rubocop#7898]
Rubocop don't see codestyle error for multiline block that started with `it`

Example:

```
before {
  1 + 1
  2 + 2
}

it {
  expect(asset.styles.compact).to_not be_blank
  expect(asset.styles.compact).to_not be_blank
  expect(asset.styles.compact).to_not be_blank
}
```

in console I enter this
```
bundle exec rubocop spec/models/
Inspecting 48 files
W...............................................

Offenses:

spec/models/asset_spec.rb:64:16: C: Style/BlockDelimiters: Avoid using {...} for multi-line blocks.
        before {
               ^
spec/models/asset_spec.rb:65:13: W: Lint/Void: Operator + used in void context.
          1 + 1
            ^

48 files inspected, 2 offenses detected
```

But for `it` blocks this is not working

**Comment by koic** [comment]
This behavior is expected. `lambda`, `proc`, `it` are ignored by default.

```yaml
Style/BlockDelimiters:
  IgnoredMethods:
    # Methods that can be either procedural or functional and cannot be
    # categorised from their usage alone, e.g.
    #
    #   foo = lambda do |x|
    #     puts "Hello, #{x}"
    #   end
    #
    #   foo = lambda do |x|
    #     x * 100
    #   end
    #
    # Here, it is impossible to tell from the return value of `lambda` whether
    # the inner block's return value is significant.
    - lambda
    - proc
    - it
```

https://github.com/rubocop-hq/rubocop/blob/v0.82.0/config/default.yml#L2380-L2396

This configure should be documented.
