### ISSUE TITLE
rubocop not looking at .rubocop.yml file at project root level

### ISSUE THREAD

**Issue by udaykadaboina** [rubocop-hq/rubocop#8218]
I just recently updated rubocop to v0.86 which has added some extra cops & changed Metrics/LineLength to Layout/LineLength

I changed that metric in my projects's root level file `.rubocop.yml` but seems like there is another rubocop.yml file in my 
**target/docker/source/.rubocop.yml** which my build tool creates as it copies this whole project & places it in /target folder. 

But it happens that rubocop(`rubocop --enable-pending-cops`) is considering the .rubocop.yml file in this nested path and ignoring the file that's in project root level. 

I have looked `target_dir` value in `RuboCop::ConfigLoader.find_project_dotfile(target_dir)` but it has the project root path in the first iteration and it changes in subsequent calls by `for` > `for_dir`. 

## Expected behavior

Doesn't the root level .rubocop.yml take precedence over .rubocop.yml file in nested folders?

## Actual behavior

rubocop is not taking .rubocop.yml in project root folder. But takes .rubocop.yml file in one of the nested folders in the project. 

## Steps to reproduce the problem

1. create a .rubocop.yml file and nest it inside some folders other than project root level. for me it was /target/source/.rubocop.yml 
```
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.3
  UseCache: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']
  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - 'db/schema.rb'
    - 'config/locales/'
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
Performance:
  Enabled: true
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: '#english-comments'
  Enabled: true
  VersionAdded: '0.9'
  VersionChanged: '0.52'
  AllowedChars: []
Style/EmptyMethod:
  Enabled: false
Style/StringLiterals:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  AutoCorrect: true
```

2. Update the rubocop gem to latest version & run the following command:
`$ rubocop --enable-pending-cops`

3. You will 
target/docker/source/.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: RuboCop found unsupported Ruby version 2.3 in `TargetRubyVersion` parameter (in target/docker/source/.rubocop.yml). 2.3-compatible analysis was dropped after version 0.81.
Supported versions: 2.4, 2.5, 2.6, 2.7

## RuboCop version

```
$ rubocop -v
0.86.0
```
