### ISSUE TITLE
Allow setting enabled cops target version instead of manually enabling every individual cop

### ISSUE THREAD

**Issue by koenpunt** [rubocop-hq/rubocop#8342]
## Is your feature request related to a problem? Please describe.

Currently when you update the rubocop dependency and new cops were introduced, you have to explicitly add these cops with `Enabled: true/false`. This results in a lot of not very useful content in the config file.

## Describe the solution you'd like

As a solution I like to propose that it's possible to enable all cops, up to a specified version. For example under the `AllCops` key:

```yml
AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.6
  TargetVersion: 0.82 # <===
```

This would enable all cops that were included in version 0.82. The cops can still be manually enabled or disabled.

And when you update the dependency in your project, you only have to update a single version number to be able to use all of the available cops.
