### ISSUE TITLE
EmptyLinesAroundAttributeAccessor and SpaceAroundMethodCallOperator are incredibly slow

### ISSUE THREAD

**Issue by JelteF** [rubocop-hq/rubocop#8348]
## Expected behavior

Running `rubocop` should only become slightly slower when enabling `Layout/EmptyLinesAroundAttributeAccessor` and `Layout/SpaceAroundMethodCallOperator`. 
 
## Actual behavior

When running `rubocop` on a 2500 line `xxx_spec.rb` file runtime of `rubocop` goes from ~3.5 seconds to ~22.5 seconds.

## Steps to reproduce the problem

Add this to your `.rubocop.yml`:
```yaml
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
```

Run it on some big `xxx_spec.rb` file and see that the runtime is now much higher.

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.87.1 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.6.6 x86_64-linux)
```
