### ISSUE TITLE
Spec errors after ConfigLoader spec

### ISSUE THREAD

**Issue by biinari** [rubocop-hq/rubocop#8548]
Specs give errors relating to `all_cops_config` keys being absent, which seems to happen after `ConfigLoader` spec is run with certain seeds.

--------

## Expected behavior

Specs should consistently pass, no matter what random seed is used and no matter what order the specs get run in.

## Actual behavior

`TargetFinder` spec fails with errors including:

```
  1) RuboCop::TargetFinder#find(..., :only_recognized_file_types) does not find hidden files
     Failure/Error:
       dir_tree_excludes = all_cops_config['Exclude'].select do |pattern|
         pattern.is_a?(String) && pattern.end_with?('/**/*')
       end

     NoMethodError:
       private method `select' called for nil:NilClass
     Shared Example Group: "common behavior for #find" called from ./spec/rubocop/target_finder_spec.rb:309
     # ./lib/rubocop/target_finder.rb:104:in `excluded_dirs'
     # ./lib/rubocop/target_finder.rb:81:in `find_files'
     # ./lib/rubocop/target_finder.rb:56:in `target_files_in_dir'
     # ./lib/rubocop/target_finder.rb:29:in `find'
     # ./spec/rubocop/target_finder_spec.rb:248:in `block (3 levels) in <top (required)>'
     # ./spec/rubocop/target_finder_spec.rb:168:in `block (3 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:31:in `block (4 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `chdir'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (3 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block (2 levels) in <top (required)>'
```

[Minimal reproduction with single examples from ConfigLoader and TargetFinder](https://gist.github.com/biinari/3f75ca1488a3cd1ef59a61aa87db5d38#file-rubocop_spec_0_minimal)

[Output for all of ConfigLoader and TargetFinder](https://gist.github.com/biinari/3f75ca1488a3cd1ef59a61aa87db5d38#file-rubocop_spec_after_configloader) - 32 failures

[Output for all specs](https://gist.github.com/biinari/3f75ca1488a3cd1ef59a61aa87db5d38#file-rubocop_spec_all) - 109 failures

## Steps to reproduce the problem

Minimal reproduction, run:

```sh
bundle exec rspec spec/rubocop/config_loader_spec.rb:1224 spec/rubocop/target_finder_spec.rb:168 --seed 10065
```

Or for the full files of ConfigLoader and TargetFinder:

```sh
bundle exec rspec spec/rubocop/config_loader_spec.rb spec/rubocop/target_finder_spec.rb --seed 10065
```

Reproduction with full spec suite:

```sh
bundle exec rspec --seed 15787
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```sh
$ bundle exec rubocop -V
0.89.1 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.4.9 x86_64-linux)

$ git rev-parse HEAD
1d2659ae47c2e1eefc1d933ca6b68b7beb128fb3
```
