### ISSUE TITLE
Slow find_files does not use Include configuration

### ISSUE THREAD

**Issue by tleish** [rubocop-hq/rubocop#8646]
A project with inline Rails engines can become slow with rubocops initial scan.  For example, a project that looks like:

```
.
├── app
├── bin
├── config
├── db
├── engines
│   └── my_engine
│       ├── app
│       ├── bin
│       ├── config
│       ├── db
│       ├── lib
│       ├── log
│       ├── node_modules
│       ├── spec
│       ├── tmp
│       └── vendor
├── lib
├── log
├── node_modules
├── public
├── spec
├── tmp
└── vendor

```

With the following configuration file:
```yaml
AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
    - 'vendor/*/**/*.rb'
    - 'Rakefile*'
    - 'engines/*/app/**/*.rb'
    - 'engines/*/config/**/*.rb'
    - 'engines/*/lib/**/*.rb'
    - 'engines/*/lib/**/*.rake'
    - 'engines/*/spec/**/*.rb'
    - 'engines/*/vendor/*/**/*.rb'
    - 'engines/*/Rakefile*'
  Exclude:
    - 'bin/*'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'app/views/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/*'
    - 'engines/*/bin/*'
    - 'engines/*/app/assets/**/*'
    - 'engines/*/app/javascript/**/*'
    - 'engines/*/app/views/**/*'
    - 'engines/*/tmp/**/*'
    - 'engines/*/node_modules/**/*'
    - 'engines/*/db/**/*'
```

--------

## Expected behavior

I would expect that the file scanning would scan the "Include" directories, and "Exclude" the directories after before analyzing.

## Actual behavior

What actually happens is rubocop scans top level root directories, then filters for Exclude patterns
1) gets a list of all directories in the root folder at one level
2) subtracts any one-level directories listed in the Exclude config
3) scans all files
4) filters based on Ruby patterns

The problem is, node_modules folder will often have thousands of files.  The root node_modules can be skipped from the initial scan, but the `engines/my_engine/node_modules` cannot be skipped in the initial filescan (based on the configuration).

Because of this, in the project I'm testing the scanning takes 7 seconds just to get the list of files.  If I scan by only 

## Steps to reproduce the problem

See description

## RuboCop version

0.77.0 (using Parser 2.6.5.0, running on ruby 2.6.5 x86_64-darwin18)

**Comment by marcandre** [comment]
Sorry about this.

There are multiple issues open about `include` and `exclude`... (e.g. #8004 ) 😢

**Comment by tleish** [comment]
Ah, thanks for the heads up.  I briefly looked before but didn't dig deep enough.  I found several now.  I'll close this one.

**Comment by tleish** [comment]
@marcandre - how would you feel about adding an optional parameter to fine-tune the initial search and loading of files for rubocop?  Something like:

```yaml
AllCops:
  GlobSearchPatterns:
    - '*'
    - 'engines/*/*'
    - '**/*.{rb,rake}'
```

Then, update `TargetFinder#find_files` with the following changes:

```ruby
def find_files(base_dir, flags)
  pattern = files_config_pattern(base_dir) || files_default_pattern(base_dir)
  Dir.glob(pattern, flags | File::FNM_EXTGLOB).select { |path| FileTest.file?(path) }
end

def files_config_pattern(base_dir)
  all_cops_config = @config_store.for(base_dir).for_all_cops
  glob_search_patterns = all_cops_config['GlobSearchPatterns']
  if glob_search_patterns
    glob_search_patterns.map { |pattern| File.join(base_dir, pattern) }
  end
end

def files_default_pattern(base_dir)
  wanted_toplevel_dirs = toplevel_dirs(base_dir, flags) -
                         excluded_dirs(base_dir)
  wanted_toplevel_dirs.map! { |dir| dir << '/**/*' }
  
  if wanted_toplevel_dirs.empty?
    # We need this special case to avoid creating the pattern
    # /**/* which searches the entire file system.
    ["#{base_dir}/**/*"]
  else
    # Search the non-excluded top directories, but also add files
    # on the top level, which would otherwise not be found.
    wanted_toplevel_dirs.unshift("#{base_dir}/*")
  end
end
```

Testing this in a large project with multiple engines and files in node_modules directories.

#### #find_files BEFORE:

Found Files: 117,812
Target Files: 413
Benchmark: 2.65 sec

#### #find_files AFTER:

Found Files: 592
Target Files: 413
Benchmark: 0.33 sec

Using Glob in the name indicates it only takes glob parameters (and not regex).

Thoughts?
