### ISSUE TITLE
Default config merge does not work

### ISSUE THREAD

**Issue by babrovka** [rubocop-hq/rubocop#8721]
`rubocop.yml` in the project does not merge inherited configuration 
from gem original [rubocop.yml](https://github.com/rubocop-hq/rubocop/blob/master/.rubocop.yml)

For example, if I would like to add path that should be excluded:

```AllCops:
  NewCops: enable
  Exclude:
    - 'some_path/**/*'
```

All originally listed paths will not be excluded anymore.

--------

## Expected behavior

Merge inherited config by default:

```
> inherit_mode:
>   merge:
>     - Exclude
```

## RuboCop version
```
0.91.0
```

**Comment by pirj** [comment]
> Does not merge inherited configuration from gem original rubocop.yml

Actually, RuboCop does not merge the `AllCops/Exclude` from `config/default.yml`, and this problem becomes apparent if you look at [RuboCop's own `.rubocop.yml`](https://github.com/rubocop-hq/rubocop/blob/0b3c8407989901641e41cb5bb66906dd8b7269ce/.rubocop.yml#L11):
```yaml
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
```

It would be really nice to merge them by default not to copy this section over and allow extensions to add their overrides as well, e.g. [`rubocop-rails` defined this](https://github.com/rubocop-hq/rubocop-rails/blob/3ec7cda08392adc7af1ffd588761aa52162a8c8d/config/default.yml#L3):
```yaml
inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
```
