### ISSUE TITLE
Style/OptionalBooleanParameter offenses are listed as auto-correctable

### ISSUE THREAD

**Issue by jafuentest** [rubocop-hq/rubocop#8755]
Here's the output I got running rubocop after updatingg

```
Offenses:

app/helpers/cards_helper.rb:3:21: C: Style/OptionalBooleanParameter: Use keyword arguments when defining method with boolean argument.
  def preview(item, full_width = false)
                    ^^^^^^^^^^^^^^^^^^
app/helpers/input_helper.rb:11:69: C: Style/OptionalBooleanParameter: Use keyword arguments when defining method with boolean argument.
  def material_switch(form, field_name, value, checked_value = nil, checked = false)
                                                                    ^^^^^^^^^^^^^^^
app/helpers/material_icons_helper.rb:19:36: C: Style/OptionalBooleanParameter: Use keyword arguments when defining method with boolean argument.
    def self.icon_join(icon, text, reverse_order = false)
                                   ^^^^^^^^^^^^^^^^^^^^^

57 files inspected, 3 offenses detected, 3 offenses auto-correctable
```

## Expected behavior

`n offenses auto-correctable` should display the correct amount of offenses that can be fixed with `rubocop -a`

## Actual behavior

It's listing all offenses as auto-correctable

## Steps to reproduce the problem

I'm not sure, I think it's specific to the `Style/OptionalBooleanParameter` cop, so it should be enough to define a method like `def do_something(bad = true)`

## RuboCop version

`0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.2, running on ruby 2.6.6 x86_64-linux)`

**Comment by marcandre** [comment]
Odd. `Style/OptionalBooleanParameter` does not auto-correct.

See also #8757 ?

**Comment by dvandersluis** [comment]
@jafuentest what's in your `.rubocop.yml`? I could not duplicate this, whether I run `rubocop -a` or `rubocop -A` it doesn't tell me anything is auto-correctable:

```console
$ bundle exec rubocop test.rb -A
Inspecting 1 file
C

Offenses:

test.rb:3:18: C: Style/OptionalBooleanParameter: Use keyword arguments when defining method with boolean argument.
def do_something(bad = true)
                 ^^^^^^^^^^

1 file inspected, 1 offense detected
```

**Comment by jafuentest** [comment]
Sorry, I forgot about it, here's my config:

```
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
    # This module is soon to be removed
    - 'app/models/user_mixins/statistics.rb'

    # Old rake tasks that exists only for future reference
    - 'doc/**/*'

    # Auto-generated binstubs
    - 'bin/*'

    # Temp files
    - 'tmp/**/*'

    # vendor dir is used by most CI services
    - 'vendor/**/*'

  TargetRubyVersion: 2.6.6

Layout/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Exclude:
    - config/routes/*.rb # Routes

Metrics/MethodLength:
  Exclude:
    - config/routes/*.rb # Routes

Metrics/BlockLength:
  Exclude:
    - config/routes/*.rb # Routes
    - config/routes.rb   # Routes
    - lib/tasks/*/*
  ExcludedMethods:
    - configure # Configurations
    - context   # Specs
    - describe  # Specs
    - namespace # Tasks
    - task      # Tasks
    - included  # Model and controller concerns
    - setup     # Devise

Metrics/ModuleLength:
  Exclude:
    - config/routes/*.rb # Routes

Rails/FindEach:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
```
