### ISSUE TITLE
Enabling NewCops in rubocop.yml does not appear to add files to exclusion with --auto-gen-only-exclude

### ISSUE THREAD

**Issue by henrytseng** [rubocop-hq/rubocop#8776]
When generating `rubocop_todo.yml` it looks enabling both new parameter `NewCops` and `--auto-gen-only-exclude` does not add files violating new rules to the exclude list.  

When adding linting to an existing project with a large code base existing files can be added to `rubocop_todo.yml`.  This makes adopting code linting easier.  With `--auto-gen-only-exclude` on and a large `--exclude-limit` new cops should be added to the `Excluded` lists under each cop in `rubocop.yml`.  

--------

## Expected behavior

Expect RuboCop to add to the `Excluded` lists in `rubocop.yml` when `NewCops` is enabled.  

## Actual behavior

Currently `NewCops` flags offenses but does not add to the `Excluded` list.  

## Steps to reproduce the problem

1. Add files with offenses included in NewCops
2. Run `rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 1000`
3. Then with newly generated `rubocop_todo.yml` run `rubocop .`

## RuboCop version

```
# rubocop -V
0.91.1 (using Parser 2.7.1.4, rubocop-ast 0.4.2, running on ruby 2.6.3 x86_64-linux-musl)
```

**Comment by dvandersluis** [comment]
Do you have more than 1000 violations of the cop? If you surpass the exclude limit, the cop will be explicitly disabled in `.rubocop_todo.yml`.

I tried to replicate this, with and without surpassing the exclude limit.

Under exclude limit:

```yaml
# Offense count: 2
# Cop supports --auto-correct.
Style/StringConcatenation:
  Exclude:
    - 'test.rb'
    - 'test2.rb'
```

Over exclude limit:

```yaml
# Offense count: 2
# Cop supports --auto-correct.
Style/StringConcatenation:
  Enabled: false
```

What are you seeing happen?
