### ISSUE TITLE
1.6.0 breaks Rubocop run

### ISSUE THREAD

**Issue by morgoth** [rubocop-hq/rubocop#9196]
I have the GH actions set as follow:
```
name: Rubocop

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: "Checkout master (base is needed to detect changed files)"
      run: git fetch origin master:master --no-tags --quiet --depth 1

    - uses: ruby/setup-ruby@v1

    - name: "Rubocop: install"
      run: gem install -N rubocop rubocop-performance rubocop-rails

    - name: "Rubocop: run"
      run: git diff --diff-filter=ACM --name-only master | xargs rubocop --format s
```

This now fails with:

```
--------Error: `Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in .rubocop.yml, please update it)
`Rails` cops have been extracted to the `rubocop-rails` gem.
(obsolete configuration found in .rubocop.yml, please update it)
```

This is also strange (run locally):
```
rubocop -v
1.6.0
rubocop -V
Error: `Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in .rubocop.yml, please update it)
`Rails` cops have been extracted to the `rubocop-rails` gem.
(obsolete configuration found in .rubocop.yml, please update it)
bundle exec rubocop -V
1.6.0 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.7.2 x86_64-linux)
  - rubocop-performance 1.9.1
  - rubocop-rails 2.9.0
```

So locally it runs fine with `bundle exec rubocop` but simple `rubocop` does not work

**Comment by bbatsov** [comment]
Hmm, seems we messed up, but I'm sure we'll manage to sort this out quickly. Seems our warnings didn't factor in the possibility that someone might be using extensions directly without a `Gemfile`. Sorry about the inconvenience! //cc @dvandersluis

**Comment by seandilda** [comment]
For anyone else searching issues, this same issue appears to be affecting Rails cops even when your rubocop.yml is requiring rubocop-rails.

**Comment by dvandersluis** [comment]
Looking into it!

**Comment by dvandersluis** [comment]
Can anyone who is experiencing this please share your .rubocop.yml requires?

**Comment by darylf** [comment]
I'm experiencing this. My require looks like:
`require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
`

**Comment by dvandersluis** [comment]
@darylf and you are running rubocop without Bundler?

**Comment by morgoth** [comment]
```
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  NewCops: enable
  # Git submodules
  Exclude:
    - docs/**/*

Performance:
  Enabled: true
Security:
  Enabled: true

# TODO
Performance/CollectionLiteralInLoop:
  Enabled: false

# Lint
Lint/AmbiguousOperator:
  Enabled: true
  Exclude:
    - test/**/*.rb
...
...
```
As described, it fails when run without a bundler.
