### ISSUE TITLE
Cannot enable rubocop-rspec derived cops on DisabledByDefault

### ISSUE THREAD

**Issue by r7kamura** [rubocop-hq/rubocop#9244]
To enable only certain cops derived from rubocop-rspec, I configured `DisabledByDefault: true` and tried to enable `RSpec/EmptyExampleGroup` like this:

```yaml
# .rubocop.yml
require:
  - rubocop-rspec

AllCops:
  DisabledByDefault: true

RSpec/EmptyExampleGroup:
  Enabled: true
```

ref: https://github.com/rubocop-hq/rubocop/pull/7923

## Expected behavior

I expected `RSpec/EmptyExampleGroup` to be enabled like this:

```console
$ bundle install
$ bundle exec rubocop
Inspecting 3 files
.C.

Offenses:

spec/example_spec.rb:2:3: C: RSpec/EmptyExampleGroup: Empty example group detected.
  context 'with empty example group' do
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

3 files inspected, 1 offense detected
```

## Actual behavior

But `RSpec/EmptyExampleGroup` is not enabled:

```console
$ bundle install
$ bundle exec rubocop
Inspecting 3 files
...

3 files inspected, no offenses detected
```

## Steps to reproduce the problem

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
```

```yaml
# .rubocop.yml
require:
  - rubocop-rspec

AllCops:
  DisabledByDefault: true

RSpec/EmptyExampleGroup:
  Enabled: true
```

```ruby
# spec/example_spec.rb
RSpec.describe 'Example' do
  context 'with empty example group' do
  end
end
```

## RuboCop version

```
$ bundle exec rubocop -V
1.6.1 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.7.2 x86_64-linux)
  - rubocop-rspec 2.0.1
```
