### ISSUE TITLE
Layout/ArgumentAlignment vs Layout/HashAlignment

### ISSUE THREAD

**Issue by one0fnine** [rubocop-hq/rubocop#9490]
Hi folks. 
I found out odd rubocop behavior. in case when it fix alignments of method attributes
Looks. A just code example
```
def do_even_more_stuff
  foo = begin
do_stuff(
            a: 1,
                   b: 2,
                   c: 3
                  )
                        rescue StandardError
                 nil
end
  foo
end
```

My rubocop settings:
```
AllCops:
  TargetRubyVersion: 3.0
  DisabledByDefault: true
  Exclude: []

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
```
And that's it.

Rubocop is finding no issues.
Although It should change alignment of `a`, `b`, `c` arguments. 

Next, i changed the config:
```
AllCops:
  TargetRubyVersion: 3.0
  DisabledByDefault: true
  Exclude: []

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
```
And It found issues : `Layout/HashAlignment: Align the keys of a hash literal if they span more than one line`
I usually use `-A` argument to fix their. So I got followed result:

```
def do_even_more_stuff
  foo = begin
do_stuff(
            a: 1,
            b: 2,
            c: 3
                  )
                        rescue StandardError
                 nil
end
  foo
end
```
I suppose the alignment of attributes is wrong.

```
$ bundle exec rubocop -V
1.9.1 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-darwin19)
  - rubocop-performance 1.9.2
```
